=== Maritims/opencargo/src/main/xsd/pricing.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:include schemaLocation="common.xsd"/>

    <xs:complexType name="PricingRuleDTO" abstract="true">
        <xs:complexContent>
            <xs:extension base="IdentifiableType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="GeographicPricingRuleDTO">
        <xs:complexContent>
            <xs:extension base="PricingRuleDTO">
                <xs:sequence>
                    <xs:element name="countrySpecification" type="CountrySpecificationType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ProductRequirementRuleDTO">
        <xs:complexContent>
            <xs:extension base="PricingRuleDTO">
                <xs:sequence>
                    <xs:element name="product" type="IdentifiableType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="WeightLimitRuleDTO">
        <xs:complexContent>
            <xs:extension base="PricingRuleDTO">
                <xs:sequence>
                    <xs:element name="maxWeight" type="PositiveDecimalType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="PricingRuleListDTO">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="geographicPricingRule" type="GeographicPricingRuleDTO"/>
            <xs:element name="productRequirementRule" type="ProductRequirementRuleDTO"/>
            <xs:element name="weightLimitRule" type="WeightLimitRuleDTO"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="PriceModifierDTO" abstract="true">
        <xs:complexContent>
            <xs:extension base="IdentifiableType">
                <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="GeographicSurchargeDTO">
        <xs:complexContent>
            <xs:extension base="PriceModifierDTO">
                <xs:sequence>
                    <xs:element name="percentage" type="PositiveDecimalType"/>
                    <xs:element name="countrySpecification" type="CountrySpecificationType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="PriceModifierListDTO">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="geographicSurcharge" type="GeographicSurchargeDTO"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="PricingPolicyDTO">
        <xs:complexContent>
            <xs:extension base="IdentifiableType">
                <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="basePrice" type="xs:decimal"/>
                    <xs:element name="priority" type="xs:int"/>
                    <xs:element name="pricingRules" type="PricingRuleListDTO"/>
                    <xs:element name="priceModifiers" type="PriceModifierListDTO" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="PricingPolicyListDTO">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="pricingPolicy" type="PricingPolicyDTO"/>
        </xs:choice>
    </xs:complexType>

    <xs:element name="pricingPolicies" type="PricingPolicyListDTO"/>
</xs:schema>

=== Maritims/opencargo/src/main/resources/pricing.xml
<?xml version="1.0" encoding="utf-8" ?>
<pricingPolicies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../xsd/pricing.xsd">
    <pricingPolicy id="1">
        <name>Foo bar</name>
        <basePrice>135.0</basePrice>
        <priority>1</priority>
        <pricingRules>
            <geographicPricingRule id="1">
                <countrySpecification>
                    <countryCode>NO</countryCode>
                </countrySpecification>
            </geographicPricingRule>
            <weightLimitRule id="2">
                <maxWeight>35.0</maxWeight>
            </weightLimitRule>
            <productRequirementRule id="3">
                <product id="3"/>
            </productRequirementRule>
        </pricingRules>
        <priceModifiers>
            <geographicSurcharge id="1">
                <name>Tillegg for transport til Svalbard</name>
                <percentage>15.0</percentage>
                <countrySpecification>
                    <countryCode>NO</countryCode>
                    <postalCodeSpecification xsi:type="PostalCodeRangeSpecificationDTO" minInclusive="9170" maxInclusive="9178"/>
                </countrySpecification>
            </geographicSurcharge>
        </priceModifiers>
    </pricingPolicy>
</pricingPolicies>
