=== Maritims/opencargo/src/main/xsd/products.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:include schemaLocation="common.xsd"/>

    <xs:complexType name="ProductType">
        <xs:complexContent>
            <xs:extension base="IdentifiableType">
                <xs:sequence>
                    <xs:element name="consignorId" type="xs:int"/>
                    <xs:element name="number" type="xs:string"/>
                    <xs:element name="name" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ProductListType">
        <xs:sequence>
            <xs:element name="product" type="ProductType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="products" type="ProductListType"/>
</xs:schema>

=== Maritims/opencargo/src/main/resources/products.xml
<?xml version="1.0" encoding="utf-8" ?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../xsd/products.xsd">
    <product id="1">
        <consignorId>1</consignorId>
        <number>5800</number>
        <name>Pakke til hentested</name>
    </product>
    <product id="2">
        <consignorId>1</consignorId>
        <number>0344</number>
        <name>Pakkeboks</name>
    </product>
    <!--<product>
        <id>2</id>
        <consignorId>1</consignorId>
        <number>5600</number>
        <name>På Døren</name>
    </product>
    <product>
        <id>3</id>
        <consignorId>1</consignorId>
        <number>5000</number>
        <name>Bedriftspakke</name>
    </product>
    <product>
        <id>4</id>
        <consignorId>1</consignorId>
        <number>4850</number>
        <name>Bedriftspakke ekspress over natten</name>
    </product>
    <product>
        <id>5</id>
        <consignorId>1</consignorId>
        <number>5100</number>
        <name>Stykkgods</name>
    </product>
    <product>
        <id>6</id>
        <consignorId>1</consignorId>
        <number>5300</number>
        <name>Stykk- og partigods</name>
    </product>-->
</products>
