=== Maritims/opencargo/src/main/xsd/rules.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:include schemaLocation="common.xsd"/>

    <xs:complexType name="RuleTargetType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="consignor" type="IdentifiableType"/>
            <xs:element name="product" type="IdentifiableType"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="BaseRuleType" abstract="true">
        <xs:complexContent>
            <xs:extension base="IdentifiableType">
                <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="priority" type="Type"/>
                    <xs:element name="targets" type="RuleTargetType"/>
                </xs:sequence>
                <xs:attribute name="number" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="RangeRuleType">
        <xs:complexContent>
            <xs:extension base="BaseRuleType">
                <xs:sequence>
                    <xs:element name="min" type="xs:decimal"/>
                    <xs:element name="max" type="xs:decimal"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="LengthOrGirthRuleType">
        <xs:complexContent>
            <xs:extension base="BaseRuleType">
                <xs:sequence>
                    <xs:element name="maxLength" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="maxCombined" type="xs:decimal" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="MinDimensionsRuleType">
        <xs:complexContent>
            <xs:extension base="BaseRuleType">
                <xs:sequence>
                    <xs:element name="minWidth" type="PositiveDecimalType" minOccurs="0"/>
                    <xs:element name="minLength" type="PositiveDecimalType" minOccurs="0"/>
                    <xs:element name="minHeight" type="PositiveDecimalType" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="GeographyRuleType">
        <xs:complexContent>
            <xs:extension base="BaseRuleType">
                <xs:sequence>
                    <xs:element name="countrySpecification" type="CountrySpecificationType" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="rules">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="geography" type="GeographyRuleType"/>
                <xs:element name="weight" type="RangeRuleType" />
                <xs:element name="width" type="RangeRuleType" />
                <xs:element name="height" type="RangeRuleType" />
                <xs:element name="length" type="RangeRuleType" />
                <xs:element name="lengthOrGirth" type="LengthOrGirthRuleType" />
                <xs:element name="minDimensions">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="BaseRuleType">
                                <xs:attribute name="minWidth" type="PositiveDecimalType"/>
                                <xs:attribute name="minHeight" type="PositiveDecimalType"/>
                                <xs:attribute name="minLength" type="PositiveDecimalType"/>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Maritims/opencargo/src/main/resources/rules.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../xsd/rules.xsd">
    <geographyRule id="1">
        <number>1</number>
        <name>Posten Norge er kun tilgjengelig i Norge</name>
        <priority>0</priority>
        <targets>
            <product id="1"/>
            <product id="2"/>
        </targets>
        <countrySpecification>
            <countryCode>NO</countryCode>
            <postalCodeSpecification xsi:type="PostalCodeRangeSpecificationDTO" minInclusive="0001" maxInclusive="9999"/>
            <postalCodeSpecification xsi:type="PostalCodeSetSpecificationDTO">
                <postalCode>3261</postalCode>
            </postalCodeSpecification>
        </countrySpecification>
    </geographyRule>
    <weightRule id="2">
        <number>2</number>
        <name>Pakke til hentested har en maksimum vekt på 35 kilo</name>
        <priority>0</priority>
        <targets>
            <product id="1"/>
        </targets>
        <max>35.0</max>
    </weightRule>
    <weightRule id="3">
        <number>3</number>
        <name>Pakkeboks har en maskimumvekt på 10 kilo</name>
        <priority>0</priority>
        <targets>
            <product id="2"/>
        </targets>
        <max>10.0</max>
    </weightRule>
    <minDimensionsRule id="3">
        <number>4</number>
        <name>Pakke til hentested har minimumsmål 15 x 10 x 1 cm</name>
        <priority>0</priority>
        <targets>
            <product id="1"/>
            <product id="2"/>
        </targets>
        <minWidth>15.0</minWidth>
        <minLength>10.0</minLength>
        <minHeight>1.0</minHeight>
    </minDimensionsRule>
    <lengthOrGirthRule id="4">
        <number>5</number>
        <name>Pakke til hentested kan enten være maksimalt 240 cm lang, eller ha en maks lengde + omkrets på 360 cm</name>
        <priority>0</priority>
        <targets>
            <product id="1"/>
            <product id="2"/>
        </targets>
        <maxLength>240.0</maxLength>
        <maxCombined>360.0</maxCombined>
    </lengthOrGirthRule>
</rules>
